share code
idanelias/Or_projects pull request #1
Opened 2021-07-16 10:57 UTC by orgrinberg

share code via pull request

2021-07-16 13:40 UTC, idanelias requested changes
overall, I think you've done a great work! see the comments in the files and fix them, especially the functions. this will help you see that some functions a repeatable between modules and can be taken to there own "udp_handler" module. but that something for project2 you'll need it more when we'll get there.

2021-07-16 13:40 UTC, idanelias commented on project1/src/udpclient.c
> +#define PORT 4080 //The port number.
defines need to be in header file

2021-07-16 13:40 UTC, idanelias commented on project1/src/udpclient.c
> +#define MAXLINE 1024 //The maximum lengh to the string.
defines need to be in header file

2021-07-16 13:40 UTC, idanelias commented on project1/src/udpclient.c
> +	sendto(sockfd, (const char *)buf, strlen(buf), MSG_CONFIRM, (const struct sockaddr *) &servaddr, sizeof(servaddr));
I can understand why MSG_CONFIRM will be at the server side, but why should this flag be set in client side.

2021-07-16 13:40 UTC, idanelias commented on project1/src/udpclient.c
> +	if ( (sockfd = socket(AF_INET, SOCK_DGRAM, 0)) == -1 )
function creating and returning a file descriptor will be cleaner.

2021-07-16 13:40 UTC, idanelias commented on project1/src/udpclient.c
> +	memset(&servaddr, 0, sizeof(servaddr));
function defining server address will be cleaner.

2021-07-16 13:40 UTC, idanelias commented on project1/src/udpclient.c
> +	close(sockfd);
code unreachable, the only way to exit the while loop is through a "return".

2021-07-16 13:40 UTC, idanelias commented on project1/src/udpserver.c
> +#define PORT 4080 //The port number.
defines should be in the header

2021-07-16 13:40 UTC, idanelias commented on project1/src/udpserver.c
> +
define should be in the header

2021-07-16 13:40 UTC, idanelias commented on project1/src/udpserver.c
> +	if ( (sockfd = socket(AF_INET, SOCK_DGRAM, 0)) == -1 )
function creating and returning a file descriptor will be cleaner.

2021-07-16 13:40 UTC, idanelias commented on project1/src/udpserver.c
> +	memset(&servaddr, 0, sizeof(servaddr));
function defining server address will be cleaner.

2021-07-16 13:40 UTC, idanelias commented on project1/src/udpserver.c
> +	if ( bind(sockfd, (const struct sockaddr *)&servaddr, sizeof(servaddr)) == -1 )
function binding the socket will be much cleaner

2021-07-16 13:40 UTC, idanelias commented on project1/include/in.h
> +/* Copyright (C) 1991-2021 Free Software Foundation, Inc.
standard libs doesn't need to be inside the include.

2021-07-16 13:40 UTC, idanelias commented on project1/include/inet.h
> +/* Copyright (C) 1997-2021 Free Software Foundation, Inc.
standard libs doesn't need to be inside the include.

2021-07-16 13:40 UTC, idanelias commented on project1/include/socket.h
> +/* Declarations of socket constants, types, and functions.
standard libs doesn't need to be inside the include.

2021-07-16 13:40 UTC, idanelias commented on project1/include/stdio.h
> +/* Define ISO C stdio on top of C++ iostreams.
standard libs doesn't need to be inside the include.

2021-07-16 13:40 UTC, idanelias commented on project1/include/stdlib.h
> +/* Copyright (C) 1991-2021 Free Software Foundation, Inc.
standard libs doesn't need to be inside the include.

2021-07-16 13:40 UTC, idanelias commented on project1/include/string.h
> +/* Copyright (C) 1991-2021 Free Software Foundation, Inc.
standard libs doesn't need to be inside the include.

2021-07-16 13:40 UTC, idanelias commented on project1/include/types.h
> +/* Copyright (C) 1991-2021 Free Software Foundation, Inc.
standard libs doesn't need to be inside the include.

2021-07-16 13:40 UTC, idanelias commented on project1/include/unistd.h
> +/* Copyright (C) 1991-2021 Free Software Foundation, Inc.
standard libs doesn't need to be inside the include.

2021-07-16 17:18 UTC, orgrinberg commented
all comment were implemented

2021-07-16 18:35 UTC, idanelias requested changes
great job! one little thing to make more sense and we are there!

2021-07-16 18:35 UTC, idanelias commented on project1/src/udpclient.c
> +	servaddr.sin_addr.s_addr = INADDR_ANY;
lines 59-61 can be joined to memsetfunc to make this function more useful. with the purpose of initiating a sockaddr_in struct.

2021-07-16 18:35 UTC, idanelias commented on project1/src/udpserver.c
> +void memsetfunc(struct sockaddr_in addr)
expand this function.

2021-07-21 23:17 UTC, idanelias approved these changes
Great job!

2021-07-21 23:17 UTC, merged